#!/usr/bin/env python3

import re
import sys
import glob

semver_patt = r"([0-9]+\.[0-9]+\.[0-9]+)"
semver_re = re.compile(semver_patt)

def find_version_py():
    found = glob.glob("*/version.py")
    if len(found) != 1:
        print("Found {} files named */version.py")
        exit(1)
    return found[0]

input, output = "CHANGELOG.md", find_version_py()

with open(input) as f:
    for line in f:
        match = semver_re.search(line)
        if match:
            version = match.groups()[0]
            print("From {} : version = {}".format(input, version))
            break

with open(output) as f:
    original = f.read()
    patched = re.sub(semver_patt, version, original)

with open(output, "w") as f:
    f.write(patched)
    print("Overwrote {}".format(output))


